name: Inkflow
targets:
  Inkflow:
    type: application
    platform: iOS
    deploymentTarget: "26.0"
    sources:
      - path: Inkflow
      - path: Generated
    resources:
      - path: Inkflow/Resources/DeepWorkChapter1.mp4


    settings:
      base:
        PRODUCT_NAME: Inkflow
        PRODUCT_BUNDLE_IDENTIFIER: app.inkflow.reader
        GENERATE_INFOPLIST_FILE: NO
        INFOPLIST_FILE: Inkflow/Info.plist
        MARKETING_VERSION: "1.0"
        CURRENT_PROJECT_VERSION: 1
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: 2XHK8UG356
        SWIFT_EMIT_LOC_STRINGS: NO
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        CODE_SIGN_ENTITLEMENTS: Inkflow/Inkflow.entitlements
        ALWAYS_SEARCH_USER_PATHS: NO
        TARGETED_DEVICE_FAMILY: "1,2"
        SWIFT_VERSION: "5.0"
      configs:
        Debug:
          ONLY_ACTIVE_ARCH: YES
    scheme:
      testTargets:
        - InkflowTests
      environmentVariables:
        'SUPABASE_ANON_KEY': 'sb_publishable_4iWHP8idnh67B74KEOAviQ_OP87uA_x'
        'SUPABASE_PUBLISHABLE_KEY': 'sb_publishable_4iWHP8idnh67B74KEOAviQ_OP87uA_x'
        'SUPABASE_URL': 'https://kagcljttmeyqexmwgfyu.supabase.co'
        'TENX_AUTH_BASE_URL': 'https://prv-8fbe26fba35f456c.preview.10x.app/auth'
        'TENX_DATA_API_URL': 'https://ep-small-dawn-atpg7xjo.apirest.c-9.us-east-1.aws.neon.tech/neondb/rest/v1'
        'TENX_PROJECT_API_URL': 'https://inkflow-api.vercel.app'
        'TENX_READY_AUTH_METHODS': 'emailPassword'
        'TENX_STORAGE_BASE_URL': 'https://prv-8fbe26fba35f456c.preview.10x.app/storage'
  InkflowTests:
    type: bundle.unit-test
    platform: iOS
    deploymentTarget: "26.0"
    sources:
      - path: InkflowTests
    dependencies:
      - target: Inkflow
    settings:
      base:
        GENERATE_INFOPLIST_FILE: YES
